services:

  mongodb:
    image: mongo:8.0.6
    ports:
      - "27017:27017"
    networks:
      - movies-network
    volumes:
      - db:/data/db
      - ./movie-backend/mongo-seed:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456


  backend:
      image: atnekoo/tp2-2383528-6222321-backend:v1
      build:
        context: ./movie-backend
      ports:
        - "8080:8080"
      networks:
        - movies-network
      depends_on:
        - mongodb
      environment:
        - SPRING_DATA_MONGODB_URI=mongodb://root:123456@mongodb:27017/movie-api-db?authSource=admin
        - SPRING_PORT=8080

  frontend:
      image: atnekoo/tp2-2383528-6222321-frontend
      build:
        context: ./movie-frontend
      ports:
        - "7777:80"
      depends_on:
        - backend
      networks:
        - movies-network

volumes:
  db:

networks:
  movies-network:
    driver: bridge